### ISSUE TITLE
Improve logging system

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmrium#2236]
```[tasklist]
### Tasks
- [x] In the general preference add an option on the first tab with 'logging level' (from trace to error). Default value 'info'.
- [x] For the 'badge' display only the number of unread messages
- [x] In the list remove the column 'Level' (keep only label)
- [x] In the list remove the column 'meta'
- [ ] In the list for the error replace by a 'copy' button. It is expected to be a stack trace if there is an error
- [x] For the 'date' just keep hoour:minute:second. You can use
- [x] Add a bullet in front of 'new' logs (the one that were not yet available last time you open the log window)
- [ ] When opening the dialog, scroll to the first 'new' log.
```

For date (in fact just time) you can use

```js
Intl.DateTimeFormat('default', {
  hour: 'numeric',
  minute: 'numeric',
  second: 'numeric'
}).format(1678859999906)
```

While logs have a uuid, keeping track of last read log may be quite complex. I think it would be easier if I add a sequential number in the log entries called id.
- https://github.com/cheminfo/fifo-logger/issues/13

**Comment by hamed-musallam** [comment]
>In the list for the error replace by a 'copy' button. It is expected to be a stack trace if there is an error

we use the objectInspector component I mean you can inspect the object directly there, is this enough or you still need to have copy button
